version: "3"
networks:
    proxy:
      external:
        name: proxy

services: 
    filebrowser:
        container_name: iso_filebrowser
        image: iso_filebrowser
        build: .
        volumes: 
            - ./config:/config
            - ./{your_data_in_host}:/repo
        user: "${UID}:${GID}"
        ports: 
            - 5017:8080
        restart: always
        networks: 
            - proxy
